cp display.png ../../../wiki/descpic/.
cp pixel.png ../../../wiki/descpic/.
cp bitmap.png ../../../wiki/descpic/.
cp box.png ../../../wiki/descpic/.
cp frame.png ../../../wiki/descpic/.
cp clear_pixel.png ../../../wiki/descpic/.
cp text_abc.png ../../../wiki/descpic/.
cp rot0.png ../../../wiki/descpic/.
cp rot90.png ../../../wiki/descpic/.
cp pl_full.png ../../../wiki/descpic/.
cp pl_upper.png ../../../wiki/descpic/.
cp pl_lower.png ../../../wiki/descpic/.
cp ascent.png ../../../wiki/descpic/.
cp descent.png ../../../wiki/descpic/.
cp abc_top.png ../../../wiki/descpic/.
cp height_all.png ../../../wiki/descpic/.
cp height_ex_text.png ../../../wiki/descpic/.
cp height_text.png ../../../wiki/descpic/.
cp linespacing_ex_text.png ../../../wiki/descpic/.
cp linespacing_text.png ../../../wiki/descpic/.
cp top_height_ex_text.png ../../../wiki/descpic/.
cp str_bbx_top2.png ../../../wiki/descpic/.
cp str_width.png ../../../wiki/descpic/.
cp xbm.png ../../../wiki/descpic/.
cp circle.png ../../../wiki/descpic/.
cp circle_ur.png ../../../wiki/descpic/.
cp menu.png ../../../wiki/descpic/.
cp line.png ../../../wiki/descpic/.
cp scale2x2.png ../../../wiki/descpic/.
