cp display.png ../../../wiki/descpic/.
cp pixel.png ../../../wiki/descpic/.
cp bitmap.png ../../../wiki/descpic/.
cp box.png ../../../wiki/descpic/.
cp frame.png ../../../wiki/descpic/.
cp clear_pixel.png ../../../wiki/descpic/.
cp text_abc.png ../../../wiki/descpic/.
cp rot0.png ../../../wiki/descpic/.
cp rot90.png ../../../wiki/descpic/.
